wiki: add --open and filemgr support

diff --git a/wiki b/wiki
--- a/wiki
+++ b/wiki
@@ -11,6 +11,8 @@ readonly ENV_OPTS="WIKI_PATH \
 									 WIKI_PAGER_OPTS \
 									 WIKI_PREVIEW_CMD \
 									 WIKI_PREVIEW_OPTS \
+									 WIKI_FILEMGR_CMD \
+									 WIKI_FILEMGR_OPTS \
 									 WIKI_GREP_OPTS"
 
 OPT_WIKI_PATH="${WIKI_PATH:-}"
@@ -19,12 +21,16 @@ OPT_WIKI_INBOX="${WIKI_INBOX:-}"
 OPT_WIKI_NEW_FILE=""
 
 OPT_WIKI_PRINT_FNAME=""
+OPT_WIKI_OPEN=""
 
 OPT_WIKI_PAGER_CMD="${WIKI_PAGER_CMD:-less}"
 OPT_WIKI_PAGER_OPTS="${WIKI_PAGER_OPTS:-}"
 
 OPT_WIKI_PREVIEW_CMD="${WIKI_PREVIEW_CMD:-cat}"
 OPT_WIKI_PREVIEW_OPTS="${WIKI_PREVIEW_OPTS:-}"
+
+OPT_WIKI_FILEMGR_CMD="${WIKI_FILEMGR_CMD:-tree}"
+OPT_WIKI_FILEMGR_OPTS="${WIKI_FILEMGR_OPTS:-}"
 
 OPT_WIKI_GREP_QUERY=""
 OPT_WIKI_GREP_OPTS="${WIKI_GREP_OPTS:--i}"
@@ -46,12 +52,16 @@ OPTIONS:
   --new, -n NAME           Create a new entry
   --inbox, -I PATH         Specify PATH where new entries are created
   --print, -f              Print the selected filename and exit
+  --open, -o               Open the wiki directory
 
   --grep, -g QUERY         Search files for QUERY
   --grep-opts OPTS         Pass in options to grep
 
   --pager, -p PAGER        Open files with PAGER
   --pager-opts OPTS        Pass in options to the pager command
+
+  --filemgr, -F FILEMGR    Open wiki directory with FILEMGR
+  --filemgr-opts OPTS      Pass in options to the file manager command
 
   --preview, -P PREVIEW    Preview files with PREVIEW
   --preview-opts OPTS      Pass in options to the preview command
@@ -91,6 +101,10 @@ parse() {
 				OPT_WIKI_PRINT_FNAME=1
 				shift
 				;;
+			--open|-o)
+				OPT_WIKI_OPEN=1
+				shift
+				;;
 			--pager|-p)
 				OPT_WIKI_PAGER_CMD="$2"
 				shift 2
@@ -105,6 +119,14 @@ parse() {
 				;;
 			--preview-opts)
 				OPT_WIKI_PREVIEW_OPTS="$2"
+				shift 2
+				;;
+			--filemgr|-F)
+				OPT_WIKI_FILEMGR_CMD="$2"
+				shift 2
+				;;
+			--filemgr-opts)
+				OPT_WIKI_FILEMGR_OPTS="$2"
 				shift 2
 				;;
 			--grep|-g)
@@ -124,21 +146,7 @@ parse() {
 }
 
 check_sanity() {
-	command -v fzf >/dev/null 2>&1 || {
-		echo >&2 "Could not find 'fzf' in your PATH"
-		return $EXIT_FAILURE
-	}
-
-	command -v "${OPT_WIKI_PAGER_CMD}" >/dev/null 2>&1 || {
-		echo >&2 "Pager command '${OPT_WIKI_PAGER_CMD}' could not be found"
-		return $EXIT_FAILURE
-	}
-
-	command -v "${OPT_WIKI_PREVIEW_CMD}" >/dev/null 2>&1 || {
-		echo >&2 "Preview command '${OPT_WIKI_PREVIEW_CMD}' could not be found"
-		return $EXIT_FAILURE
-	}
-
+	# Ensure wiki path is set and exists
 	[ -n "${OPT_WIKI_PATH}" ] || {
 		echo >&2 "Please set WIKI_PATH or use --path"
 		return $EXIT_FAILURE
@@ -148,8 +156,42 @@ check_sanity() {
 		echo >&2 "${OPT_WIKI_PATH} does not exist"
 	}
 
+	# Ensure fzf exists
+	command -v fzf >/dev/null 2>&1 || {
+		echo >&2 "Could not find 'fzf' in your PATH"
+		return $EXIT_FAILURE
+	}
+
+	# Ensure pager is set and exists
 	[ -n "${OPT_WIKI_PAGER_CMD}" ] || {
-		echo >&2 "Please set WIKI_PAGER or use --pager"
+		echo >&2 "Please set WIKI_PAGER_CMD or use --pager"
+		return $EXIT_FAILURE
+	}
+
+	command -v "${OPT_WIKI_PAGER_CMD}" >/dev/null 2>&1 || {
+		echo >&2 "Pager command '${OPT_WIKI_PAGER_CMD}' could not be found"
+		return $EXIT_FAILURE
+	}
+
+	# Ensure preview command is set and exists
+	[ -n "${OPT_WIKI_PREVIEW_CMD}" ] || {
+		echo >&2 "Please set WIKI_PREVIEW_CMD or use --preview"
+		return $EXIT_FAILURE
+	}
+
+	command -v "${OPT_WIKI_PREVIEW_CMD}" >/dev/null 2>&1 || {
+		echo >&2 "Preview command '${OPT_WIKI_PREVIEW_CMD}' could not be found"
+		return $EXIT_FAILURE
+	}
+
+	# Ensure file manager is set and exists
+	[ -n "${OPT_WIKI_FILEMGR_CMD}" ] || {
+		echo >&2 "Please set WIKI_FILEMGR_CMD or use --filemgr"
+		return $EXIT_FAILURE
+	}
+
+	command -v "${OPT_WIKI_FILEMGR_CMD}" >/dev/null 2>&1 || {
+		echo >&2 "File manager command '${OPT_WIKI_FILEMGR_CMD}' could not be found"
 		return $EXIT_FAILURE
 	}
 }
@@ -184,6 +226,14 @@ main() {
 
 	parse "$@"
 	check_sanity
+
+	[ -z "$OPT_WIKI_OPEN" ] || {
+		"${OPT_WIKI_FILEMGR_CMD}" \
+			"${OPT_WIKI_FILEMGR_OPTS}" \
+			"${OPT_WIKI_PATH}"
+
+		return $EXIT_SUCCESS
+	}
 
 	# FIXME
 	if [ -n "$OPT_WIKI_NEW_FILE" ]; then
